#!/usr/bin/python
#
# Called by git-commit with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, make this file executable.

try:
    import sys, datetime, os

    versionpy = '/var/dev/freeems/version.py'

    # Build revision line
    revision = datetime.datetime.today().strftime('__revision__ = \'r%Y%m%d%H%M%S\'\n')
    print revision

    # Load version.py for reading
    sourcefile = open(versionpy, 'r')
    sourcelines = sourcefile.readlines() 
    sourcefile.close()

    # Look for revision line
    found = False

    x = -1
    for line in sourcelines:
        x += 1
        if line.startswith('__revision__'):
            # Grab only version number from line, and remove leading "r"
            sourcelines[x] = revision
            found = True
            break

    # Fail now if we cannot find revision
    if not found:
        print 'Could not find revision in version.py'
        sys.exit(1)

    # Load version.py for reading
    sourcefile = open(versionpy, 'w')
    sourcefile.writelines(sourcelines)
    sourcefile.close()

    print 'Written new revision number to file'

    # Re-add to commit
    os.execvp('git', ('git', 'add', 'version.py'))


except Exception, e:
    raise
    sys.exit(1)
